# Generated by Django 3.0.4 on 2020-03-28 11:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExt',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('pin_sprite', models.PositiveIntegerField(default=1)),
                ('geopin_sprite', models.PositiveIntegerField(default=1)),
                ('unlocked_pins', models.TextField(blank=True, default='1', validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('unlocked_geopins', models.TextField(blank=True, default='1', validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('achievements', models.TextField(blank=True, default='', validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('profile_pic_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
