# Generated by Django 3.0.4 on 2020-03-29 11:15

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(unique=True)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('pin_sprite', models.PositiveIntegerField(default=1)),
                ('geopin_sprite', models.PositiveIntegerField(default=1)),
                ('unlocked_pins', models.TextField(blank=True, default='1', validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('unlocked_geopins', models.TextField(blank=True, default='1', validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('achievements', models.TextField(blank=True, default='', validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('profile_pic_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UserExt',
        ),
    ]
