# Generated by Django 3.0.4 on 2020-04-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_auto_20200410_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='money',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
