# Generated by Django 3.0.4 on 2020-04-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_profile_money'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='unlocked_geopins',
        ),
        migrations.AddField(
            model_name='profile',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='geopin_sprite',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
