# Generated by Django 3.0.4 on 2020-05-23 08:38

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_auto_20200414_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='unlocked_pins',
            field=models.TextField(blank=True, default='1,2', validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
