name: Django CI/CD

on:
  push:
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        coverage run --source='.' manage.py test -v 3
        coverage report --skip-covered | grep TOTAL
        
    - name: Deploy to Heroku
      uses: AkhileshNS/heroku-deploy@v3.0.4
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_email: "gordiig@gmail.com"
        heroku_app_name: "gordiig-rsoi-users"
